config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :chats do
    member do
      post :set_current_chat
    end
  end

  root 'chats#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  after_create_commit { broadcast_prepend_to 'chats' }
  after_update_commit { broadcast_replace_to 'chats' }
  after_destroy_commit { broadcast_remove_to 'chats' }

  belongs_to :user
  validates :history, presence: true, on: :update

  before_update :request_answer

  attr_accessor :question

  private

  def request_answer

    return if self.question.blank?

    response = Gemini::Client.send_message(self.question)
    reply = response.dig('candidates', 0, 'content', 'parts', 0, 'text') || response['error'] || "Sorry, I don't understand"
    self.history['massages'] << { "role": 'bot', "content": reply }
    enqueue_add_question_job
  end

  def enqueue_add_question_job
    return if self.question.blank?

    AddQuestionJob.perform_async(id, history.deep_stringify_keys)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :chats, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # before_action :set_current_user

  # def set_current_user
  #  current = current_user if user_signed_in?
  # end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: %i[ show edit update destroy set_current_chat]

  # GET /chats or /chats.json
  def index
    @chats = Chat.where(user_id: current_user.id).order(updated_at: :desc)
    @chat = Chat.new
  end

  # GET /chats/1 or /chats/1.json
  def show
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats or /chats.json
  def create
    @chat = Chat.new(chat_params)
    @chat.user_id = current_user.id

    if @chat.save
      session[:current_chat_id] = @chat.id
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.prepend('chats', partial: 'chat', locals: { chat: @chat }),
            turbo_stream.replace('chat_content', partial: 'current_chat', locals: { chat: @chat }),
            turbo_stream.replace('question_input', partial: 'add_question', locals: { chat: @chat })
          ]
        end
        format.html { redirect_to chats_path, notice: 'Tt was successfully created.' }
      end
    else
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace('new_chat', partial: 'form', locals: { chat: @chat }) }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1 or /chats/1.json
  def update
    payload = if @chat.history.nil?
                puts 'history not present'
                { massages: [{ "role": 'user', "content": chat_params[:question] }] }

              else
                puts 'history present'
                { massages: @chat.history['massages'] << { "role": 'user', "content": chat_params[:question] }}

              end
    @chat.question = chat_params[:question]

    respond_to do |format|
      if @chat.update(history: JSON.parse(payload.to_json))
        puts 'updated chat in controller'
        format.html { redirect_to @chat, notice: 'Chat was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat }
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace('chat_content', partial: 'current_chat', locals: { chat: @chat }),
          ]
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1 or /chats/1.json
  def destroy
    @chat.destroy!

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@chat) }
      format.html { redirect_to chats_url, notice: 'Chat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_current_chat
    session[:current_chat_id] = @chat.id
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace('chat_content', partial: 'current_chat', locals: { chat: @chat }),
          turbo_stream.replace('question_input', partial: 'add_question', locals: { chat: @chat })]
      end
    end

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_chat
    @chat = Chat.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def chat_params
    params.require(:chat).permit(:user_id, :history, :question)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/_add_question.html.erb
<!--  <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="button-addon2">-->
<!--  <button class="btn btn-outline-secondary" type="button" id="button-addon2">Button</button>-->

<%= form_with(model: chat, url: chat_path(chat), method: :patch, id: dom_id(chat), class: "form-group", data: { turbo_frame: dom_id(chat), 'turbo-method' => :post, controller: "question-submit", action: "turbo:submit-start->question-submit#submitStart turbo:submit-end->question-submit#submitEnd" }) do |form| %>
  <div class="row mt-5">
    <div class="col">
      <div class="input-group mb-3 mt-5">
        <%= form.text_field :question,
                            class: "form-control",
                            placeholder: 'enter your question',
                            aria: { label: 'question', describedby: "button-question" },
                            data: { question_submit_target: "input" },
                            required: true
        %>

        <%= form.button 'Add',
                        type: :submit,
                        class: "btn btn-outline-secondary",
                        id: "button-question",
                        data: { question_submit_target: "button" } %>

      </div>
    </div>
    <div class="col-1 mt-5 d-none" data-question-submit-target="spinner">
      <div class="spinner-border text-primary" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>
  </div>
<% end %>

app/views/chats/_chat.html.erb
<%= turbo_frame_tag dom_id(chat) do %>
  <div class="row">
    <div class="col">
      <%= link_to (chat.history.nil? || chat.history.dig("massages",0,"content").nil? ? "chat_#{chat.id}" : chat.history.dig("massages",0,"content")),
                  set_current_chat_chat_path(chat),
                  data: { 'turbo-method' => :post },
                  class: "btn btn-outline-secondery w-100"
      %>
    </div>
    <div class="col">
      <%= link_to "X", chat_path(chat), data: { turbo_method: :delete,  turbo_confirm: "Are you sure?" },class: "btn btn-outline-secondery w-100" %>
    </div>
  </div>
<% end %>

app/views/chats/_chats.html.erb
<%= turbo_frame_tag "chats" do %>

  <%= render @chats %>
<% end %>

app/views/chats/_current_chat.html.erb
<div id="chat_content" class="mt-5 mb-5 p-5" data-controller="scroll" data-scroll-target="scroll">
  <% unless chat.history.nil? %>
    <% chat.history.dig('massages').each do |c| %>
      <div class="row justify-content-center">
        <div class="col-10 h-auto">
          <% if c['role'] == "user" %>
            <div class="row  mt-5 mb-1 ">
              <div class="col-6  ">
                You:
              </div>
            </div>
            <div class="row">
              <div class="col-6 bg-primary rounded-4 p-4 ">
                <%= c['content'] %>
              </div>
            </div>
          <% else %>
            <div class="row justify-content-end mt-5  mb-1">
              <div class="col-6  ">
                Bot:
              </div>
            </div>
            <div class="row justify-content-end">
              <div class="col-6 bg-secondary  rounded-4 p-4 ">
                <%= c['content'] %>
              </div>
            </div>
          <% end %>

        </div>

      </div>
    <% end %>
  <% else %>
    <div class="row justify-content-center">
      <div class="col-10 h-auto">
        <div class="row  mt-5 mb-1 ">
          <div class="col-6  ">
            Bot:
          </div>
        </div>
        <div class="row">
          <div class="col-6 bg-secondary rounded-4 p-4 ">
            <%= "Hello, I am a bot. How can I help you?" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/chats/_form.html.erb
<%= form_with(model: chat, id: dom_id(chat), class: "form-group") do |form| %>
  <% if chat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% @chat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :history, style: "display: block" %>
    <%= form.text_field :history %>
  </div>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<% content_for :title, "Editing chat" %>

<%= turbo_frame_tag dom_id(@chat) do %>

  <%= render "add_question", chat: @chat %>

<% end %>

<!--<h1>Editing chat</h1>-->

<%#= render "form", chat: @chat %>

<!--<br>-->

<!--<div>-->
<!--  <%#= link_to "Show this chat", @chat %> |-->
  <%#= link_to "Back to chats", chats_path %>
<!--</div>-->

app/views/chats/index.html.erb
<% content_for :title, "Chats" %>

<div class="row align-self-stretch w-100">
  <div class="col-2 bg-secondary h-100 h-auto d-inline-block text-center ">

    <div class="row justify-content-center">
      <div class="col-10  mt-3 ">
        <%= link_to "New Chat", chats_path(chat: { user_id: current_user.id}), data: { turbo_frame: 'new_chat', turbo_method: :post}, class: "btn btn btn-outline-light w-100" %>
      </div>
    </div>

    <%= turbo_frame_tag "new_chat" %>
    <%= turbo_frame_tag 'chats' do %>
      <%= render @chats%>
    <% end %>

  </div>
  <div class="col-10">
    <div class="row">
      <h1>Chats</h1>
    </div>
    <div class="row align-self-stretch w-100">
      <div class="col h-75 ">
        <div class="col h-75 ">
          <% if @chats.any? %>
            <%= render partial: 'current_chat', locals: { chat: @chats.first} %>
          <% else %>
          <div id="chat_content"></div>
          <% end %>
          </div>
      </div>
    </div>
    <div class="row fixed-bottom justify-content-center ">
      <div class="col-9 offset-2">
        <div  id="question_input">
          <%= render partial: "add_question", locals: { chat: @chats.first} if @chats.any?  %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/chats/new.html.erb
<% content_for :title, "New chat" %>

<%= turbo_frame_tag "new_chat" do %>
  <%= render "form", chat: @chat %>
<% end %>

app/views/chats/show.html.erb
<%= turbo_frame_tag dom_id(@chat) do %>
  <%= render @chat %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsChatBot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module", defer: true %>
  </head>

  <body>

    <%= render partial: 'layouts/shared/navbar' %>
    <div class="container-fluid d-flex vh-100">
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Chatbot</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Logout" , destroy_user_session_path, data: { "turbo-method": :delete }, class:"nav-link active", aria_current:"page"   if current_user %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<%= form_with(model: user, id: dom_id(user), class: "form-group") do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container border rounded mb-3 mt-2">
    <div class="row mt-2">
      <div class="col text-end">
        <%= link_to 'X', user, class: "btn btn-secondary" %>
      </div>
    </div>
    <div class="row mt-1">
      <div class="form-group col-md-5 col-sm-6 ">
        <%= form.label :email %>
        <%= form.email_field :email, autofocus: true, required: true, autocomplete: "new-email", class: "form-control" %>
      </div>
    </div>
    <div class="row mt-1">
      <div class="form-group col-md-4 col-sm-6">
        <%= form.label :password %>
        <%= form.password_field :password, required: user.new_record?, minlength: 4, autocomplete: "new-password", class: "form-control" %>
      </div>
      <div class="form-group col-md-4 col-sm-6">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, required: user.new_record?, minlength: 4, autocomplete: "new-password", class: "form-control" %>
      </div>
    </div>


    <div class="row mt-3 mb-3">
      <div class="col">
        <%= form.submit class: "btn btn-primary " %>
      </div>
      <div class="col text-end">
        <% unless action_name == 'new' || action_name == 'create' %>
          <%= link_to 'trash', user, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<%= turbo_frame_tag dom_id(user) do %>
  <div class="container border rounded mb-3">
    <div class="row mt-3 mb-3">
      <div class="col-5">
        <strong>Email:</strong>
        <%= user.email %>
      </div>
      <div class="col text-end">
        <%= link_to 'edit', edit_user_path(user) %>
      </div>
    </div>
    <div class="row mt-3 mb-3">
      <div class="col-5">
        <strong>created at:</strong>
        <%= user.created_at.strftime("%d/%m/%Y") %>
      </div>
  </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<%= turbo_stream_from "users" %>
<%= render @users %>

app/views/users/edit.html.erb
<div class="container">
  <div class="header">
    <h1>Edit user</h1>
  </div>
  <%= turbo_frame_tag dom_id(@user) do %>
    <%= render "form", user: @user %>
  <% end %>
  <div class="row mt-2">
    <div class="col">
      <%= link_to "Show user", user_path(@user), class: 'btn btn-primary' %>
    </div>
    <div class="col text-end">
      <%= link_to "Back to users", users_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <%= turbo_frame_tag 'users' do %>
    <div class="row">
      <div class="col-10">
        <h1>Users</h1>
      </div>
    </div>
    <div class="col-2 text-end">
      <%= link_to 'New user', new_user_path, class: 'btn btn-primary' %>
    </div>
    <div class="mt-2">
      <%= render 'users' %>
    </div>
  <% end %>
  </div>

app/views/users/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to users"), users_path %>

  <div class="header">
    <h1>New user</h1>
  </div>
  <%= turbo_frame_tag "first_turbo_frame" do %>
  <%= render "form", user: @user %>
    <% end %>
</main>

app/views/users/show.html.erb
<%= turbo_frame_tag dom_id(@user) do %>
  <%= render @user %>
<% end %>
<div class="container">
  <div class="row mt-2">
    <div class="col">
      <%= link_to "Edit user", edit_user_path(@user), class: 'btn btn-primary' %>
    </div>
    <div class="col text-end">
      <%= link_to "Back to users", users_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>